Add sampler
vhive-serverless/invitro pull request #274
Opened 2023-09-27 10:33 UTC by cvetkovic

2023-09-27 11:48 UTC, ustiugov commented on README.md
> +InVitro is a set of tools for conducting research in serverless computing. It consists of the sampler and the loader. The sampler is used for creating a representative workload summary from a real wo
```suggestion
In-Vitro is a set of tools for analyzing the performance of serverless cluster deployments. In-Vitro consists of two tools, namely sampler and loader. Sampler creates representative workload summaries (i.e., samples of functions) based on production traces. Loader reconstructs the invocation traffic based on a given trace and steers this load to the functions deployed in the studied serverless cluster. Currently, In-Vitro supports [vHive](LINK) and [OpenWhisk](LINK).
```

provide links to vHive and OpenWhisk

2023-09-27 11:50 UTC, ustiugov commented on README.md
> +
this doc needs to have the following subsections:
- license, etc (see vHive)
- Pointers to the quickstart and other first-order docs

2023-09-27 11:52 UTC, ustiugov commented on docs/loader.md
> +The token needs `repo` and `admin:public_key` permissions and will be used for adding SSH key to the user's account for
now all repos are public but you may keep this note in the bottom of the doc

2023-09-27 11:57 UTC, ustiugov commented on .github/workflows/preprocessing_tests.yaml
> +    name: Preprocessing tests
```suggestion
    name: Sampler preprocessing tests
```

2023-10-02 07:27 UTC, ustiugov commented
Please give this one a priority. We need to start advertising the work ASAP

2023-10-02 07:46 UTC, ustiugov requested changes
a couple of comments, otherwise lgtm

2023-10-02 07:46 UTC, ustiugov commented on docs/loader.md
> +* The execution unit is approximately 100 `SQRTSD` x86 instructions.
can we get this replaced by a simple albeit cross-platform counter increment? please raise an issue

2023-10-02 07:46 UTC, ustiugov commented on README.md
> +The software is maintained at the [EASL lab](https://systems.ethz.ch/research/easl.html) at ETH Zürich.
```suggestion
The software is maintained by the [EASL lab](https://systems.ethz.ch/research/easl.html) at ETH Zürich.
```

2023-10-02 07:47 UTC, ustiugov commented
@leokondrashov please provide your review as well. particularly, check the READMEs and how clear they are

2023-10-02 09:59 UTC, leokondrashov requested changes
Looked over READMEs, left couple comments.

2023-10-02 09:59 UTC, leokondrashov commented on README.md
> -## Running on Cloud Using Serverless Framework
This part got lost in movement to new docs.

2023-10-02 09:59 UTC, leokondrashov commented on docs/sampler.md
> +The reference traces are stored in the `reference_traces` branch of this repo in the root folder, as a `samples.tar.gz`
This refers to the sampler branch. Will this be added as well or should we just add it to this repo's LFS?

2023-10-02 09:59 UTC, leokondrashov commented on docs/sampler.md
> +**Note:** Currently plotting is broken and has been disabled. (Issue 77)
As well, referencing the Issue from the old sampler repo. Should we transfer issues?

2023-10-02 10:29 UTC, merged