Cluster manager to merge
vhive-serverless/invitro pull request #284
Opened 2023-10-11 13:20 UTC by cvetkovic

## Summary

A small summary of the requirements (in one/two sentences).

## Implementation Notes :hammer_and_pick:

* Briefly outline the overall technical solution. If necessary, identify talking points where the reviewer's attention should be drawn to.

## External Dependencies :four_leaf_clover:

* 

## Breaking API Changes :warning:

* 

*Simply specify none (N/A) if not applicable.*

2023-10-12 09:56 UTC, Lightxyz requested changes

2023-10-12 09:56 UTC, Lightxyz commented on pkg/driver/deployment.go
> +		"scaling_upper_bound": {"1"},
Scaling upper and lower bounds should be based on some config

2023-10-13 07:03 UTC, leokondrashov commented on pkg/config/parser_test.go
> +		config.IATDistribution != "equidistant" ||
May be we should fixate the configs that are used for tests and move them to separate folder, so we won't need to update these tests that often.

BTW, why do we need to update the default config? Is there something wrong?

2023-10-17 14:48 UTC, Lightxyz approved these changes

2023-10-17 20:44 UTC, cvetkovic commented
Let's postpone merging until the tutorial on Monday is done.

2023-10-24 14:38 UTC, merged