solve the label issue of singlenode through affinity
vhive-serverless/invitro pull request #413
Opened 2024-04-18 18:22 UTC by wanghanchengchn

# solve the label issue of singlenode through affinity

## Summary

For multi-node clusters, we label nodes with three values for loader-nodetype: master, monitoring, and worker. In the single-node case, we cannot label the node with all three of them, which leads to issues with placement. To address this, we propose to use the node affinity option instead of node selectors. This should allow us to choose one of the labels.

## Implementation Notes :hammer_and_pick:

1. Create a new label: `singlenode`, to identify single-node instances.
2. Update the node selectors in the following three places to use node affinity with the old label and the new `singlenode` label:
   - Knative services (master)
   - Prometheus (monitoring)
   - Worker pods (worker)

## External Dependencies :four_leaf_clover:

N/A

## Breaking API Changes :warning:

N/A

2024-05-03 11:34 UTC, leokondrashov requested changes

2024-05-03 11:34 UTC, leokondrashov commented on scripts/setup/rewrite_yaml_files.sh
> +    (
Previous section deletes the affinity. Can you make it into a single assignment instead of cleaning and appending the affinity field?

2024-05-03 11:34 UTC, leokondrashov commented on scripts/setup/create_multinode.sh
> +    server_exec $MASTER_NODE 'kubectl apply -f ~/loader/config/enable_affinity.yaml'
Now, you can remove the nodeselector that is on line 258.

2024-05-03 11:34 UTC, leokondrashov commented on scripts/setup/create_singlenode_container.sh
>      $DIR/expose_infra_metrics.sh $SERVER
Make this conditional as it is done in setup_multinode (based on DPELOY_PROMETHEUS)

2024-05-03 11:34 UTC, leokondrashov commented on scripts/setup/setup.cfg
> +VHIVE_BRANCH='main'
Don't change the branch to main. We should either wait for new vhive version or negotiate a release of a new version.

2024-05-08 01:46 UTC, leokondrashov commented
LGTM, but please rebase on top of the main branch and fix the e2e test. There is a command in that test that enables nodeselect; now, it should enable the affinity. Ignore the link check test; that's an issue with a link for the Azure Trace unrelated to the PR.

2024-05-10 05:31 UTC, leokondrashov commented
We released new vHive version with needed change in setup_tool. You can update the branch to v1.7.1 and rebase on main.

2024-06-13 09:02 UTC, cvetkovic commented
@leokondrashov, @wanghanchengchn: Is this PR still relevant? Should we finalize it?

2024-06-13 09:07 UTC, leokondrashov commented
Yeah, I think it is good now. Just need to rebase

2024-06-13 09:39 UTC, cvetkovic approved these changes

2024-06-13 09:43 UTC, cvetkovic commented
You can go ahead with merging. I'll fix the linter in a separate PR.

2024-06-13 09:47 UTC, leokondrashov approved these changes

2024-06-13 09:48 UTC, merged