Added the mapper tool to map trace to vSwarm proxies
vhive-serverless/invitro pull request #541
Opened 2024-10-30 15:17 UTC by KarthikL1729

Added documentation for the mapper tool.

## Summary

A small summary of the requirements (in one/two sentences).

The mapper tool is used to map the Azure trace functions to the vSwarm proxy functions based on the profiles of vSwarm functions and their correlation with the Azure trace function durations and memory utilization.

## Implementation Notes :hammer_and_pick:

* Briefly outline the overall technical solution. If necessary, identify talking points where the reviewer's attention should be drawn to.

This PR adds the mapper tool, which loads the function duration and memory trace with Pandas, finds the optimal mapping based on modelling the problem as a linear sum assignment, and then outputs a file which maps each HashFunction in the trace to a proxy function in vSwarm. The profile needs to be unzipped before using the mapper, and the profile is included in a tar.gz file in the mapper directory.

## External Dependencies :four_leaf_clover:

* N/A

## Breaking API Changes :warning:

* N/A

*Simply specify none (N/A) if not applicable.*

2024-11-01 11:34 UTC, leokondrashov requested changes
This a very brief look into a single function of the mapper. Please fix all of possible problems before submitting the PR.

2024-11-01 11:34 UTC, leokondrashov commented on tools/mapper/find_proxy_function.py
> +            trace_functions, err = get_closest_proxy_function(
That is extremely unexpected behavior. If something goes sideways in the unique assignment, I'll get a non-unique one. I would be pretty annoyed to find that my tool tried to be too smart about the operation that I asked it to do. If operation is not possible, the tool should just exit.

2024-11-01 11:34 UTC, leokondrashov commented on tools/mapper/find_proxy_function.py
> +        proxy_functions = OrderedDict(proxy_functions)
Again, why do you need ordereddict here?

2024-11-01 11:34 UTC, leokondrashov commented on tools/mapper/find_proxy_function.py
> +                    break
You linearly search in the dict. Are sure that this data structure is suitable for the task? You also literally created trace_list that has all of them in the index order.

2025-01-24 08:21 UTC, JooyoungPark73 requested changes

2025-01-24 08:21 UTC, JooyoungPark73 commented on docs/mapper_cdf.png
Please change the axis label to CDF

2025-01-24 08:21 UTC, JooyoungPark73 commented on docs/mapper.md
> +As mentioned previously, the maximum function duration that we can achieve with vSwarm functions is near 27 seconds, and so, for the WD plot, we exclude trace functions that are beyond this duration
Are you planning to mention that you will fill mock functions for the functions that are not mapped?

2025-01-24 10:33 UTC, KarthikL1729 commented on docs/mapper.md
> +As mentioned previously, the maximum function duration that we can achieve with vSwarm functions is near 27 seconds, and so, for the WD plot, we exclude trace functions that are beyond this duration
I've mentioned that previously in the doc, line 63.

2025-01-26 06:39 UTC, JooyoungPark73 submitted a review, later dismissed

2025-01-30 11:18 UTC, leokondrashov commented on requirements.txt
> +typing
Please fix the version to specific ones

2025-01-30 11:21 UTC, leokondrashov commented on docs/mapper.md
> +Currently, vSwarm does not have full coverage of the Azure trace functions. To make sure that we do not have a high error in the mapping of functions, we set a hard threshold of 40% as the maximum ab
```suggestion
Currently, vSwarm does not have full coverage of the Azure trace functions. To make sure that we do not have a high error in the mapping of functions, we set a hard threshold of 40% as the maximum absolute error (from the actual trace function duration) that a proxy function can have to be mapped to a trace function. If we do not find an eligible function for the mapping from vSwarm, we fall back to using standard InVitro trace functions in their place for those functions alone.
```

2025-01-30 11:28 UTC, leokondrashov commented on docs/mapper.md
> +- Number of mapped functions with higher than 40% duration error (replaced by InVitro sample functions)
Can you provide reference numbers for the full trace mapping? That would be helpful to see the ballpark of the possible errors.

2025-01-30 11:29 UTC, leokondrashov commented on docs/mapper.md
Overall, please reduce the amount of passive voice in docs

2025-01-30 11:38 UTC, leokondrashov commented on tools/mapper/mapper.py
> +        log.critical(f"Load Generation failed")
Please work on the error messages. In most cases, message says "Load Generation failed". I have no idea what that means in the context of mapper, it doesn't generate the load. Overall, you have a ton of error checking which end up with the same error message from user perspective.

2025-01-30 11:41 UTC, leokondrashov commented on tools/mapper/mapper.py
> +    if invoke:
This parameter has confusing name. We don't invoke from `generate_plot`.

2025-01-30 11:41 UTC, leokondrashov commented on tools/mapper/mapper.py
> +        return trace_durations, mapped_durations
A lot of duplicated code and repeated hard-coded constant

2025-01-30 11:42 UTC, leokondrashov commented on docs/mapper.md
> +usage: mapper.py [-h] -t TRACE_DIRECTORYPATH -p PROFILE_FILEPATH [-o OUTPUT_FILEPATH] [-u UNIQUE_ASSIGNMENT]
This line is inconsistent with the rest of the help message.

2025-01-30 11:44 UTC, leokondrashov commented on tools/mapper/find_proxy_function.py
> +        return trace_functions, -1
What exceptions are expected here?

2025-01-30 11:46 UTC, leokondrashov commented on tools/mapper/find_proxy_function.py
> +        f"Lower the correlation value, the proxy function is a better proxy of the trace function"
What does this line mean?

2025-01-30 11:58 UTC, KarthikL1729 commented on tools/mapper/mapper.py
> +        return trace_durations, mapped_durations
This code is from the WD distance branch, and so I mainly used it for the metric generation. Shall I remove it entirely? Since the mapper does not use it.

2025-02-05 02:50 UTC, JooyoungPark73 approved these changes

2025-02-05 03:18 UTC, JooyoungPark73 requested changes

2025-02-05 03:18 UTC, JooyoungPark73 commented on .github/workflows/tools-tests.yaml
> +          python3 tools/mapper/mapper.py -t tools/mapper/test_files/20 -p tools/mapper/profile.json
Please compare with sample correct mapping

2025-02-05 03:47 UTC, leokondrashov commented on tools/mapper/test_files/trace.tar.gz
This is a very small archive used only for tests. How big are the files inside? If it is comparable with the example trace, we can just add the files directly. It would be even better if you could use the example trace for the test.

2025-02-05 03:47 UTC, leokondrashov commented on .github/workflows/tools-tests.yaml
> +          python3 -c "import json; json.load(open('tools/mapper/profile.json'))"
Wait, is the profile.json the only file in the archive? If so, can you use `gzip` directly? `tar` is commonly used to archive folders.

2025-02-05 03:47 UTC, leokondrashov commented on tools/mapper/mapper.py
> +        with open(output_filepath, "w") as jf:
Why do you write it twice? I think it is better to add a stage of filtering and error counting on the same data structure (better to extract to separate functions with tests, preferably).

2025-02-05 03:47 UTC, leokondrashov commented on tools/mapper/mapper.py
> +        trace_functions[hash_function]["memory"] = row
Why do you need to create the dict from dataframe? All these actions can be done with `.set_index` and `.concat`

2025-02-05 03:47 UTC, leokondrashov commented on tools/mapper/mapper.py
> +        return trace_durations, mapped_durations
If you have a thoughts that it is useful, leave and document it. If it is completely useless, remove

2025-02-05 12:23 UTC, KarthikL1729 commented on tools/mapper/mapper.py
> +        trace_functions[hash_function]["memory"] = row
I wanted to return a unified data structure from the load trace with the duration data and memory data clearly separated. Before this step the duration and memory data re in two separate dataframes, so I would still need to make a new consolidated dataframe, and I thought a dict would be simpler. Would the consolidated dataframe be preferred?

2025-02-05 14:29 UTC, leokondrashov commented on tools/mapper/mapper.py
> +        trace_functions[hash_function]["memory"] = row
You can join dataframes by index (BTW, hash function is not guaranteed to be unique. You should use (owner, app, function) to be sure). You can add suffixes for the columns with the same name so you can address them individually.

2025-02-10 02:56 UTC, leokondrashov approved these changes
Looks fine to me. @cvetkovic Please take a look

2025-02-10 02:56 UTC, leokondrashov commented on docs/mapper.md
> +### Usage
Please put the note about unzipping the profile.json

2025-02-10 05:26 UTC, JooyoungPark73 approved these changes

2025-02-10 08:55 UTC, cvetkovic commented on docs/mapper_cdf.png
What do the tail and sharp drop from 10^4 to 2.5*10^6 mean?

2025-02-10 16:58 UTC, KarthikL1729 commented on docs/mapper_cdf.png
That is because the vSwarm functions have a maximum of 27 seconds run time. The current graph shows the mapping accuracy up to 10^6 seconds, but drops the functions that are longer than 27 seconds in the sampled trace. I'll update that to not drop the functions beyond 27 seconds, and then the graph should be clearer.

2025-02-10 17:12 UTC, KarthikL1729 commented on docs/mapper_cdf.png
I am unsure about what the sharp drop is, I think that is an artifact of using plt.hist from matplotlib.

2025-02-12 03:37 UTC, leokondrashov commented on docs/mapper_cdf.png
You can cut it with xlim, to leave the drop is outside of the plot, so no one is confused about that

2025-02-14 03:49 UTC, leokondrashov commented
Looks good to me. Please squash the commits and rebase on main branch properly. @cvetkovic approve it if you are good with that.

2025-02-14 10:11 UTC, cvetkovic submitted a review, later dismissed

2025-02-17 02:49 UTC, leokondrashov approved these changes

2025-02-17 02:50 UTC, merged